services:
  base:
    build:
      context: .
      dockerfile: base.Dockerfile

  pre-build:
    build:
      context: .
      dockerfile: pre-build/Dockerfile
    container_name: pre-build
    volumes:
      - ./ignore:/app/ignore

  main_bot:
    build:
      context: .
      dockerfile: main_bot/Dockerfile
    container_name: main_bot
    env_file:
      - .env


  web:
    build:
      context: .
      dockerfile: web_app/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./ignore:/app/ignore
    depends_on:
      - pre-build
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/sosi-serega.ru:/etc/letsencrypt/live/sosi-serega.ru:ro
      - /etc/letsencrypt/archive/sosi-serega.ru:/etc/letsencrypt/archive/sosi-serega.ru:ro
      - /etc/letsencrypt/renewal:/etc/letsencrypt/renewal:ro
    depends_on:
      - web
